language: android

jdk: oraclejdk8

sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

script:
- ./gradlew assembleDebug
